language: ruby
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - jruby-9.1.2.0
  - rbx-2
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
before_install:
  - gem query -i -n ^bundler$ -v'>=1.12.5' >/dev/null || gem install bundler
install:
  - sudo apt-get update && sudo apt-get install --force-yes socat
script:
  - bundle install
  - CODECLIMATE_REPO_TOKEN=70754a8aa666790236dbbb910727648f4dbb1f73a28f886d0b0c9e39a36b5a79 bundle exec rspec -fd
